blank_issues_enabled: false
contact_links:
  - name: Lniri Complete Setup Template & Configuration Guide
    url: https://github.com/AbsolOrg/Lniri/blob/main/template.md
    about: Please consult the documentation and troubleshooting guide before opening an issue.
